# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: OlxSanMarcos Api 
  description: Descripcion de la api OlxSanMarcos
  version: "1.0.0"
# the domain of the service
host: localhost:8000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api
resourcePath: /apiyml
produces:
  - application/json
paths:
  /products:
    get:
      summary: Lista de Productos
      description: 
        Retorna la lista de todos los productos
      parameters:
        - name: name
          in: query
          description: Nombre del producto
          required: true
          type: string
          format: string
        - name: description
          in: query
          description: Descripcion del producto
          required: true
          type: string
          format: double
      tags:
        - Products
      responses:
        200:
          description: Array de Productos
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Error inesperado
          schema:
            $ref: '#/definitions/Error'


definitions:
  Product:
    type: object
    properties:
      _id:
        type: string
        description: Identificador unico
      description:
        type: string
        description: Descripcion del Producto.
      name:
        type: string
        description: Nombre del producto
 
 
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
